;; Each new term in the Fibonacci sequence is generated by adding
;; the previous two terms.
;;
;; By starting with 1 and 2, the first 10 terms will be:
;;
;; `1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...`
;;
;; By considering the terms in the Fibonacci sequence whose values
;; do not exceed four million, find the sum of the even-valued terms.


;; ##Solution
;; To obtain the Fibonacci sequence given in the problem description I
;; can use this recursive function which takes an empty collection, the
;; first and second items in the sequence, and also the limit
(defn fib-seq [result previous current limit]
  (if (> previous limit)
    result
    (let [next-n (+ previous current)]
      (recur (conj result previous) current next-n limit))))

(fib-seq [] 1 2 100)                  ; => [1 2 3 5 8 13 21 34 55 89]

;; Then, I need to filter the results to find its even items
(filter even? (fib-seq [] 1 2 100))   ; (2 8 34)

;; And finally perform the sum
(reduce
  + (filter
      even? (fib-seq [] 1 2 100)))    ; 44


;; ##Putting it together
;; The `fib-seq` function is now an auto-executable function inside
;; `sum-fib-evens-until`
(defn sum-fib-evens-until [limit]
  " Returns the sum of all even numbers in a Fibonacci sequence until 
    the specified limit."
  (reduce
    + (filter
        even? ((fn [result previous current limit]
                 (if (> previous limit)
                   result
                 (let [next-n (+ previous current)]
                   (recur (conj result previous) current next-n limit))))
                 [] 1 2 limit))))

;; Sum of evens until 100
(sum-fib-evens-until 100)               ; 44

;; ##Answer
(def ans (sum-fib-evens-until 4000000)) ; 4613732

(println ans)

